### ISSUE TITLE
Explanation of page is required.

### ISSUE THREAD

**Issue by chainhead** [sthnaqvi/explorer#2]
When launched, the fields for Gas Limit, Block Time and Current Diff are stuck at `Loading...`. There is a price comparison between KCN and ETH. What is KCN? How can I make it show USD? 

Also, the current block is stuck at zero. When does it change?

**Comment by sthnaqvi** [comment]
You need a working geth full node (if private geth node then miner should be started) in order for this to work. Your geth node needs to be synced as well.

P.S. KCN is KaraCoin, it is a new blockchain, it was committed here by mistake, You can check out http://karachain.io to know more about it

**Comment by chainhead** [comment]
Thank you, @sthnaqvi Do you have a repo without KCN code committed?

**Comment by chainhead** [comment]
@sthnaqvi I ran a full node with the Ropsten test network. However, I still do not see all the stats updated. Can you please suggest what am I missing?

```
geth --rpc --mine --networkid "3" --rpcaddr "localhost" --rpcport "8545" --rpcapi "web3,eth" --rpccorsdomain "http://localhost:8545"
```

BTW, I tried this with your other repository too - sthnaqvi/ethereum-blockchain-explorer - no luck! In fact, the screen-shot in sthnaqvi/ethereum-blockchain-explorer does not mention KCN/USD exchange rate. But, when I launch the home page, I can see the same exchange rate.

**Comment by sthnaqvi** [comment]
if you want to run ropsten full geth node, run with this command:-
`geth  --testnet --rpc --rpcaddr="0.0.0.0" --rpcport "8545" --rpcapi "eth,web3" --rpccorsdomain "*"`

`rpccorsdomain "*"` for add domain if you only open for specific domain then replace * with domain name .
Like if you only open for your localhost block explorer then `--rpccorsdomain "http://localhost:8000"`

**Comment by chainhead** [comment]
`--rpcaddr="0.0.0.0" --rpccorsdomain "*"` is not a good idea. Any other suggestions?

**Comment by sthnaqvi** [comment]
No not any other suggestions , I already ran geth via above command
