### ISSUE TITLE
App doesnt run, just shows web folder.. wrong folder running from package.json

### ISSUE THREAD

**Issue by gateway** [sthnaqvi/explorer#5]
Went though the whole install process on a hosted server.

Did the following:

- installed node.js 8.11.2
- npm version 5.6.0
- cloned the depo.
- npm install - all files installed properly.
- npm start - ran without issues

output

![image](https://user-images.githubusercontent.com/519563/40563889-51c93d6a-601b-11e8-8295-94e042386ee7.png)

Installed nginx as a reverse proxy.. see https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04#set-up-nginx-as-a-reverse-proxy-server

This is a standard way to make sure when users hit the web site which runs on port 80, all the commands get redirected to localhost:8000 where the app is running.

Went to my domain and instead of the app I saw the actual folder structure, this lead me to check the folder and well the index.html is missing in /app folder.. I also noticed that a lot of this stuff has been moved to docs/  

I edited package.json to load /docs instead of app.  This works but pulls in data from else where.. (im still going though the code)

Also I see errors in the log files 

```
[Fri May 25 2018 20:02:31 GMT+0000 (UTC)] "GET /vendor_js/angular.min.js.map" Error (404): "Not found"
[Fri May 25 2018 20:02:31 GMT+0000 (UTC)] "GET /vendor_js/angular-moment.min.js.map" Error (404): "Not found"
[Fri May 25 2018 20:02:31 GMT+0000 (UTC)] "GET /vendor_js/angular-sanitize.min.js.map" Error (404): "Not found"
[Fri May 25 2018 20:02:31 GMT+0000 (UTC)] "GET /vendor_js/angular-route.min.js.map" Error (404): "Not found"


```

So im not 100% sure yet for the reason to not run app.. if so lets remove it and fix the package.json to point to docs as long as everything has the ability to be configured to load what ever geth server..

just a fyi.. I may work on a pull request but still digging though this..

**Comment by ryanluce** [comment]
I'm having the same issue.

**Comment by ryanluce** [comment]
Got it working by adding this file(index.html) https://github.com/sthnaqvi/explorer/blob/ecadedf6ad067b4980337b8d64c80c8837c6b5b0/app/index.html

**Comment by sthnaqvi** [comment]
Please don't change  package.json from  ./app to /docs because /docs folder only use for demo purposes demo host on GitHub pages with the link : [https://explorer.ethorbit.com](https://explorer.ethorbit.com)

To run explorer open terminal/cmd change directory to project root folder and just run **npm install** then **npm start**

**Comment by gateway** [comment]
Your missing the point, the current depo has the index.html missing in the /app folder.. so their is no way to run the code.. I think adding that in would fix the issue.. :)

**Comment by sthnaqvi** [comment]
@gateway I'm getting your point, I'll fix the issue.
