### ISSUE TITLE
May I know this project only for main-net of ETH ,how about testnet & rinkeby?

### ISSUE THREAD

**Issue by nearlai** [sthnaqvi/explorer#7]
May I know this project only for main-net of ETH ,how about testnet & rinkeby?

**Comment by sthnaqvi** [comment]
@nearlai, this project is not only for main-net of ETH, Project was tested with all ethereum testnet network.
You can run this project with any testnet network only change **[geth rpc](https://github.com/sthnaqvi/explorer/blob/9a67c9adaa32f8515becec15021d9d0a990b35a3/app/app.js#L86)**
