### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by asdasdasda1245** [sthnaqvi/explorer#9]
root@VM-2ff7e19a-1df2-426c-9db0-1d731cc33358:~/Golib/src/github.com/sthnaqvi/explorer# npm start

> eth-block-explorer@0.0.1 prestart /home/dyjr/Golib/src/github.com/sthnaqvi/explorer
> npm install

npm WARN lifecycle eth-block-explorer@0.0.1~postinstall: cannot run in wd %s %s (wd=%s) eth-block-explorer@0.0.1 bower install /home/dyjr/Golib/src/github.com/sthnaqvi/explorer
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 4.424s

> eth-block-explorer@0.0.1 start /home/dyjr/Golib/src/github.com/sthnaqvi/explorer
> http-webnode ./app -a 192.168.100.151 -p 8000 -c-1

Starting up http-webnode, serving ./app
Available on:
  http://192.168.100.151:8000
Hit CTRL-C to stop the server
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /assets/css/main.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/jquery/dist/jquery.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/moment/locale/de.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/jquery/dist/jquery.min.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/moment/locale/de.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/web3/dist/web3.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular/angular.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/web3/dist/web3.min.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular/angular.min.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/moment/moment.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/bootstrap/dist/js/bootstrap.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/moment/moment.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular-route/angular-route.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/bootstrap/dist/js/bootstrap.min.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular-route/angular-route.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular-bootstrap/ui-bootstrap.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular-bootstrap/ui-bootstrap.min.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular-sanitize/angular-sanitize.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular-sanitize/angular-sanitize.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular-moment/angular-moment.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /bower_components/angular-moment/angular-moment.js" Error (404): "Not found"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /scripts/controllers/addressInfosController.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /scripts/controllers/chainInfosController.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /scripts/controllers/mainController.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /scripts/controllers/blockInfosController.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /scripts/controllers/transactionInfosController.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
[Tue Apr 16 2019 14:01:00 GMT+0800 (CST)] "GET /app.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"

**Comment by sthnaqvi** [comment]
@asdasdasda1245, please run `bower install` to install bower dependency
